version: '3.8'

services:
  backend_services:
    build:
      context: . # Assuming the Dockerfile and all necessary code are in the current directory or a subdirectory
      dockerfile: Dockerfile # The Dockerfile must be configured to include all applications and run them
    # List all ports required by the individual applications
    ports:
      - "9100:9100" # Port for the main dashboard backend (originally backend_services)
      - "9000:9000" # Port for the progress tracker (originally progress_tracker)
      - "9001:9001" # Port for the user session service (originally user_session)
    networks:
      - lab_network # Connect to the shared network

networks:
  # Define the network
  lab_network:
    driver: bridge