version: '3.8'
services:
  testing_frameworks:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8016-8020:8016-8020"
    networks:
      - lab_network

networks:
  lab_network:
    driver: bridge