version: '3.8'
services:
  project_management:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001-8005:8001-8005"
    networks:
      - lab_network

networks:
  lab_network:
    driver: bridge